template = "meeting_link.html"
recipients = "python_for_str_engg_registrations.xlsx"
subject = 'SEA Tech Talk "Python for Structural Engineers" - Google Meet link and schedule'
attachment = "python_for_structural_engineers.pdf"

